version: 2
updates:
  - package-ecosystem: "npm"
    directory: "."
    schedule:
      interval: "daily"
    versioning-strategy: increase
    groups:
      npm:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "daily"
    groups:
      gha:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "."
    schedule:
      interval: "daily"
    versioning-strategy: increase
    groups:
      npm:
        patterns:
          - "*"
  - package-ecosystem: "docker-compose"
    directory: "."
    schedule:
      interval: "daily"
    versioning-strategy: increase
    groups:
      npm:
        patterns:
          - "*"