services:
  vite:
    build:
      context: .
      dockerfile: Dockerfile.vite
    ports:
      - "5173:5173"
  nwjs:
    build:
      context: .
      dockerfile: Dockerfile.nwjs
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
