FROM ubuntu:rolling@sha256:102bc1874fdb136fc2d218473f03cf84135cb7496fefdb9c026c0f553cfe1b6d
WORKDIR /app/pomodoro
# Install required packages
RUN apt update
RUN apt install -y libglib2.0-0
RUN apt install -y libnss3
RUN apt install -y libdbus-1-3
RUN apt install -y libatk1.0-0
RUN apt install -y libcups2
RUN apt install -y libdrm2
RUN apt install -y libatspi2.0-0
RUN apt install -y libxcomposite1
RUN apt install -y libxdamage1
RUN apt install -y libxfixes3
RUN apt install -y libxrandr2
RUN apt install -y libgbm1
RUN apt install -y libxkbcommon0
RUN apt install -y libpango-1.0-0
RUN apt install -y libcairo2
RUN apt install -y libasound2t64
RUN apt install -y xvfb
RUN apt install -y libatomic1
RUN apt install -y curl
RUN apt install -y xorg
# Install Volta package manager
RUN curl https://get.volta.sh | bash
ENV VOLTA_HOME="/root/.volta"
ENV PATH="$VOLTA_HOME/bin:$PATH"
RUN volta install node@23
# Install dependencies
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 5173
CMD ["npm", "run", "dev"]
